#!/usr/bin/env bash
# Installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Server block containing the custom header
SERVER_CONFIG=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://lexroverse.tech/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-available/default"
service nginx restart
