#!/usr/bin/env bash
#Using the while command to echo "Best School" 10 times and "Hi" the 9th time
i="0"
while [ $i -lt 10 ];do 
    echo "Best School" 
    i=$((i+1))

    if [ $i -eq 9 ];then
    echo 'Hi'
    
    fi

done
