#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 20
i="1"
while [ $i -lt 21 ]; do
    echo "$i"
    i=$((i+1))

    if [ $i -eq 5 ]; then
        echo "bad luck from China"
    
    fi

    if [ $i -eq 10 ]; then
        echo "bad luck from Japan"
    
    fi

    if [ $i -eq 18 ]; then
        echo "bad luck from Italy"
    
    fi

done